### ISSUE TITLE
Save bug - Almost entire map change wiped, character forgotten.

### ISSUE THREAD

**Issue by BjarkiFreyr95** [pipliz/ColonySurvival#174]
I have been working on the same map for a while now or at least 100 hours making it. Last time I played it was yesterday (25/12/17). Now today, when I entered the save I found out that my entire building was gone. My inventory, my colony, my everything is not there anymore. However I can see it is the same map (The starting map) and there are some changes that I made to it that had not been overwritten. Somehow the game did overwrite my entire fortress and replaced it with how the game started. There are no backup files. 
- After last update everything was fine.
- As my building got larger I started experiencing more and more lag (framedrops).
- My computer did not crash the last time I played the game.
- .... I am not kidding about the 100+ hours.
![image](https://user-images.githubusercontent.com/16037293/34361191-db0b00c2-ea5f-11e7-9e55-dbba59133db5.png)
This was a print screen taken around a week ago. 
![image](https://user-images.githubusercontent.com/16037293/34361260-5094b720-ea60-11e7-8cda-c822ab301240.png)
This is how it looks like now. 
Here is a picture of why I believe your saving system is corrupted.
![image](https://user-images.githubusercontent.com/16037293/34361313-d80e16e2-ea60-11e7-916e-03d9f8d166f6.png)
Somehow some of my changes are still there (I'm underground in flight mode in this picture). 

I do realize that you probably don't do backup save files and there is probably no chance for me to retrieve my save, however it would be nice if you could look into this so this does not happen to others.

- Please do not say it is my fault not creating backups because this is a programmers bug, not some mistake I did. 
- I can give you more specific details on this If you are interested.

**Comment by pipliz** [comment]
It is very likely the server for one reason or the other shut down improperly (crash, error, whichever). This likely happened while it was saving this specific area (which left a file that is barely written to, clearing the area). It could be a bug causing this bug - I'm not entirely sure.

Assuming you were playing version 0.5.0:

There is a chance to recover (parts of) the save file. Look in the files inside of the savegame and see if there is any file with .old or .new filetypes (specifically in the regions folder, could be in others as well).

The game should attempt to write the new data to "somechunk.csregion.new", then upon completion rename "somechunk.csregion" to "somechunk.csregion.old" and then copy the .csregion.new over the .csregion, then delete the csregion.old.

So if there is a .new or .old file with substantial size (not 0 bytes) you can try renaming it from say "Region_47_1_28.csregion.32424.new" to "Region_47_1_28.csregion", overwriting the newly created csregion file with the older backup.

This .old / .new thing is in the game since 0.4 I believe, and is also the case for the json files since 0.5. 0.5 also added autosaving for the majority of the data.

I do have to make a system to automatically detect & recover such files upon launching the server.

**Comment by BjarkiFreyr95** [comment]
There were no backed up files (neither .old or .new). 
My game has never crashed tho and I've never had an error.

Thank you for your response.
