### ISSUE TITLE
"Starting Server" black screen

### ISSUE THREAD

**Issue by MONK1E** [pipliz/ColonySurvival#23]
Whenever I try to create a single player world, I am greeted with a black screen which displays "Starting Server" and a timer on the bottom right of my screen, I've waited over 10 minutes on this screen of which I've not had any progress.

I've attempted to play multiplayer to see if that would work yet it just results in my game crashing without loading any servers. I have uninstalled and downloaded the game multiple times, verified my files and rebooted my PC yet I'm still facing the same problem.

My PC has specs far higher than those required to run the game so I don't believe that could be the problem. Hopefully you can shine some light on this situation as the game looks to be the sort that I could really enjoy.

**Comment by pipliz** [comment]
Hi there, thanks for the report. I'm hearing similar problems from other people.

Can you upload the log files from "colony survival/colonyclient_data/output_log.txt" and "colony survival/colonyserver_data/output_log.txt"?

Otherwise, is there a chance you're running an antivirus program that'll firewall the server, preventing it from connecting to the client?
