### ISSUE TITLE
Berry Farm plotting bug

### ISSUE THREAD

**Issue by Tehslaughterhaus** [pipliz/ColonySurvival#46]
Found an issue with the plotting for berry farming. It seems that when placing berry farms in certain directions the maximum and minimum dimensions change. These are some of these screenshots I got to show this.

-View of the entire building with plots
![20170725145703_1](https://user-images.githubusercontent.com/30449253/28596401-3cd6c084-714d-11e7-86db-90f89b03dc6e.jpg)

-A side that can take 7x6 but not 5x6
![20170725145748_1](https://user-images.githubusercontent.com/30449253/28596442-673e7f92-714d-11e7-9649-7ffafd9883a9.jpg)

![20170725145725_1](https://user-images.githubusercontent.com/30449253/28596463-7fa8b11a-714d-11e7-97cc-ec65d962ac15.jpg)

-The other side that can take 5x6 but not 7x6
![20170725145735_1](https://user-images.githubusercontent.com/30449253/28596486-9c44f414-714d-11e7-8ab5-73cbfd59fc3b.jpg)

![20170725145739_1](https://user-images.githubusercontent.com/30449253/28596489-9fe56ffe-714d-11e7-876f-e7bb2bcf2926.jpg)

**Comment by pipliz** [comment]
This problem is probably due to the way berry bushes are placed at the moment. The farmer always stands at one side of it, requiring an additional row/column on that axis. 

As in, theoretically you could make a 26x1 farm with 13 bushes, with 13 places next to it to stand at. But you can't make a 1x26 farm with 13 bushes, as the farmer would try to stand outside of it. (I don't think this actually works ingame, but okay)
